# Generated by Django 3.0.6 on 2020-10-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouptext', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=64)),
                ('dest_phone', models.CharField(max_length=64)),
                ('src_phone', models.CharField(max_length=64)),
                ('message_id', models.CharField(max_length=120)),
                ('message_status', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
